FROM node:18-alpine
WORKDIR /app/frontend

# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci

COPY . .

# disable telemetry at run time
ENV NEXT_TELEMETRY_DISABLED 1

RUN npm run build

CMD ["npm", "run", "start"]