services:
  db:
    image: postgres
    expose:
      - 5432
    environment:
      - POSTGRES_USER=faust
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=EduContractSystem
    volumes:
      - pg_data:/var/lib/postgresql/data
      - pg_backups:/pg_backups
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  server:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    volumes:
      - ./backend:/app/backend
    depends_on:
      db:
        condition: service_healthy
  client:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - server

volumes:
  pg_data: {}
  pg_backups: {}

