services:
  db:
    image: postgres
    expose:
      - 5432
    environment:
      - POSTGRES_USER=faust
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=EduContractSystem
    volumes:
      - pg_data:/var/lib/postgresql/data
      - pg_backups:/pg_backups
  server:
    build: .
    command: python -m uvicorn config.asgi:application --host 0.0.0.0
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  client:
    build: ./frontend/
    command: npm run start
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  pg_data: {}
  pg_backups: {}

