# Generated by Django 5.0.3 on 2024-03-31 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosingDocumentsReference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='наименование', verbose_name='наименование')),
                ('type', models.TextField(db_column='тип', verbose_name='тип')),
                ('template', models.TextField(db_column='шаблон', verbose_name='шаблон')),
            ],
            options={
                'db_table': 'СправочникТиповЗакрывающихДокументов',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='наименование', verbose_name='наименование')),
                ('contract', models.TextField(db_column='договор', verbose_name='договор')),
                ('year', models.IntegerField(db_column='год', verbose_name='год')),
                ('status', models.TextField(db_column='статус', verbose_name='статус')),
            ],
            options={
                'db_table': 'Договора',
            },
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='наименование', verbose_name='наименование')),
                ('template', models.TextField(db_column='шаблон', verbose_name='шаблон')),
            ],
            options={
                'db_table': 'ШаблонДоговора',
            },
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.TextField(db_column='наименование_краткое', verbose_name='наименование краткое')),
                ('full_name', models.TextField(db_column='наименование_полное', verbose_name='наименование полное')),
                ('INN', models.DecimalField(db_column='ИНН', decimal_places=0, max_digits=12, verbose_name='ИНН')),
                ('KPP', models.DecimalField(db_column='КПП', decimal_places=0, max_digits=9, verbose_name='КПП')),
                ('bank_name', models.TextField(db_column='наименование_банка', verbose_name='наименование банка')),
                ('BIC', models.TextField(db_column='БИК', verbose_name='БИК')),
                ('correspondent_account', models.DecimalField(db_column='корр/счет', decimal_places=0, max_digits=20, verbose_name='корр/счет')),
                ('checking_account', models.DecimalField(db_column='р/с', decimal_places=0, max_digits=20, verbose_name='р/с')),
                ('personal_account', models.TextField(db_column='л/с', verbose_name='л/с')),
                ('head_first_name', models.TextField(db_column='имя', verbose_name='имя')),
                ('head_last_name', models.TextField(db_column='фамилия', verbose_name='фамилия')),
                ('head_middle_name', models.TextField(db_column='отчество', verbose_name='отчество')),
                ('head_pos_first_name', models.TextField(db_column='имяр', verbose_name='имяр')),
                ('head_pos_last_name', models.TextField(db_column='фамилияр', verbose_name='фамилияр')),
                ('head_pos_middle_name', models.TextField(db_column='отчествор', verbose_name='отчествор')),
                ('reason', models.TextField(db_column='основание', verbose_name='На основании чего действует руководитель')),
            ],
            options={
                'db_table': 'Контрагент',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('counterparty', models.TextField(db_column='учреждение', verbose_name='учреждение')),
                ('reason', models.TextField(db_column='назначение_платежа', verbose_name='назначение платежа')),
                ('date', models.DateField(db_column='дата_оплаты', verbose_name='дата оплаты')),
                ('price', models.DecimalField(db_column='сумма_оплаты', decimal_places=2, max_digits=10, verbose_name='сумма оплаты')),
            ],
            options={
                'db_table': 'ПоступающиеОплаты',
            },
        ),
        migrations.CreateModel(
            name='ServicesReference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='наименование_услуги', verbose_name='наименование услуги')),
                ('price', models.DecimalField(db_column='цена', decimal_places=2, max_digits=14, verbose_name='цена')),
                ('year', models.IntegerField(db_column='год', verbose_name='год')),
            ],
            options={
                'db_table': 'СправочникУслуг',
            },
        ),
        migrations.CreateModel(
            name='ContractsHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contract', models.TextField(db_column='договор', verbose_name='договор')),
                ('version', models.IntegerField(db_column='версия', verbose_name='версия')),
                ('status', models.TextField(db_column='статус', verbose_name='статус')),
                ('contract_id', models.ForeignKey(db_column='id_договора', on_delete=django.db.models.deletion.CASCADE, to='contracts.contract', verbose_name='id договора')),
            ],
            options={
                'db_table': 'ИсторияДоговоров',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='template',
            field=models.ForeignKey(db_column='шаблон', on_delete=django.db.models.deletion.CASCADE, to='contracts.contracttemplate', verbose_name='шаблон'),
        ),
        migrations.AddField(
            model_name='contract',
            name='counterparty',
            field=models.ForeignKey(db_column='контрагент', on_delete=django.db.models.deletion.CASCADE, to='contracts.counterparty', verbose_name='контрагент'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='service',
            field=models.ForeignKey(db_column='услуга', on_delete=django.db.models.deletion.CASCADE, to='contracts.servicesreference', verbose_name='услуга'),
        ),
        migrations.CreateModel(
            name='ClosingDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.TextField(db_column='номер', verbose_name='номер')),
                ('date', models.DateField(db_column='дата', verbose_name='дата')),
                ('document', models.TextField(db_column='документ', verbose_name='документ')),
                ('type', models.ForeignKey(db_column='тип_документа', on_delete=django.db.models.deletion.CASCADE, to='contracts.closingdocumentsreference', verbose_name='тип документа')),
                ('contract', models.ForeignKey(db_column='договор', on_delete=django.db.models.deletion.CASCADE, to='contracts.contract', verbose_name='договор')),
                ('service', models.ForeignKey(db_column='услуга', on_delete=django.db.models.deletion.CASCADE, to='contracts.servicesreference', verbose_name='услуга')),
            ],
            options={
                'db_table': 'ЗакрывающиеДокументы',
            },
        ),
    ]
