# Generated by Django 4.2.11 on 2024-04-07 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='closingdocument',
            options={'verbose_name': 'Закрывающий документ', 'verbose_name_plural': 'Закрывающие документы'},
        ),
        migrations.AlterModelOptions(
            name='closingdocumentsreference',
            options={'verbose_name': 'Тип закрывающего документы', 'verbose_name_plural': 'Типы закрывающих документов'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Договор', 'verbose_name_plural': 'Договора'},
        ),
        migrations.AlterModelOptions(
            name='contractshistory',
            options={'verbose_name': 'История договора', 'verbose_name_plural': 'История договоров'},
        ),
        migrations.AlterModelOptions(
            name='contracttemplate',
            options={'verbose_name': 'Шаблон договора', 'verbose_name_plural': 'Шаблоны догворов'},
        ),
        migrations.AlterModelOptions(
            name='counterparty',
            options={'verbose_name': 'Контрагент', 'verbose_name_plural': 'Контрагенты'},
        ),
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name': 'Поступление оплаты', 'verbose_name_plural': 'Поступления оплаты'},
        ),
        migrations.AlterModelOptions(
            name='servicesreference',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Справочник услуг'},
        ),
    ]
