# Generated by Django 4.2.7 on 2023-12-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='version',
            field=models.IntegerField(db_column='версия', default=1, verbose_name='версия'),
            preserve_default=False,
        ),
    ]
