# Generated by Django 4.2.7 on 2023-12-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contracts_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='contract_id',
            field=models.IntegerField(db_column='id_договора', default=1, verbose_name='id договора'),
            preserve_default=False,
        ),
    ]
