# Generated by Django 4.2.7 on 2023-12-20 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contracts_contract_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracts',
            name='contract_id',
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='version',
        ),
        migrations.CreateModel(
            name='ContractsHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contract', models.TextField(db_column='договор', verbose_name='договор')),
                ('version', models.IntegerField(db_column='версия', verbose_name='версия')),
                ('status', models.TextField(db_column='статус', verbose_name='статус')),
                ('contract_id', models.ForeignKey(db_column='id_договора', on_delete=django.db.models.deletion.CASCADE, to='contracts.contracts', verbose_name='id договора')),
            ],
            options={
                'db_table': 'ИсторияДоговоров',
            },
        ),
    ]
