# Generated by Django 5.0.4 on 2024-05-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contracttemplate_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract',
            field=models.JSONField(db_column='договор', verbose_name='договор'),
        ),
    ]
