# Generated by Django 5.0.3 on 2024-03-28 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_remove_contracts_contract_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contracts',
            new_name='Contract',
        ),
    ]
