# Generated by Django 5.0.3 on 2024-03-28 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_rename_contracts_contract'),
    ]

    operations = [
        migrations.RenameModel('Counterpartie', 'Counterparty'),
    ]
